= HiveMQ Community Edition with Extended Authentication SDK Support

image:https://www.hivemq.com/img/svg/hivemq-ce.svg[HiveMQ Community ,500, align="left"]

HiveMQ CE is a Java-based open source MQTT broker that fully supports MQTT 3.x and MQTT 5. 

It is the foundation of the HiveMQ Enterprise Connectivity and Messaging Platform and implements all MQTT features. This project is the technical core of many of the largest MQTT deployments and is now available as Open Source Software under the Apache 2 license.

* Web Site: https://www.hivemq.com/
* Documentation:https://github.com/hivemq/hivemq-community-edition/wiki
* Community Forum: https://community.hivemq.com/
* Contribution Guidelines: link:CONTRIBUTING.adoc[Contributing.adoc]
* License: The source files in this repository are made available under the link:LICENSE[Apache License Version 2.0].

= This fork

This fork just extends the HiveMQ broker to expose the MQTTv5 extended authentication support features to the extension SDK.
The features are already built into the broker but there is no support for them into the SDK.
Currently the SDK only supports the simple authentication method for both MQTTv3 and MQTTv5 but AUTH packets can't be used yet.
This fork allows an authenticator to extend from ExtendedAuthenticator that can request further information from the client by sending an AUTH packet and finally make the decision after the response AUTH is received.

= How to use

== Building from source

=== Prerequisites
At least Java version 11 is required to build and run HiveMQ CE.

If you are in doubt, you can check the installed Java version by entering `java -version` on your command line.

=== Building the binary package

Check out the git repository and build the binary package.
[source,bash]
----
git clone https://github.com/michaelg9/hivemq-community-edition.git

cd hivemq-community-edition

./gradlew clean packaging
----

The package `hivemq-ce-<version>.zip` is created in the sub-folder `build/zip/`.


== Start
Unzip the created binary package 

[source,bash]
----
cd hivemq-ce-<version>

./bin/run.sh
----

= License

HiveMQ Community Edition is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE[here].

